server:
  port: 7777
spring:
  jackson:
    time-zone: GMT+8
  datasource:
    # 连接池实现的限定名，这里使用hikari连接池。一般不用配置这个，会自动去类路径下加载，这是一个可选的配置。
    #    type: com.zaxxer.hikari.HikariDataSource
    # 数据库的驱动JDBC驱动程序的类全限定名，它其实会根据下面的url配置自动检测，这是一个可选配置。
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库的JDBC链接
    url: jdbc:mysql://localhost:3306/kono
    # 数据库用户名
    username: root
    # 数据库密码
    password: 123456
  redis:
    host: localhost
    port: 6379
  cache:
    type: REDIS
    redis:
      time-to-live: 120
      # mybatis plus 配置
mybatis-plus:
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
    # 扫描 xml 文件位置
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      # 使用雪花算法主键填充策略
      id-type: assign_id

logging:
  level:
    # 打印SQL日志
    cn.felord.kono.mapper: debug
oss:
  aliyun:
    active: true
    access-key-id: LTAI4GH2E345QmJDrAGvWNH
    access-key-secret: XjDpNn5JqHXGL3xIebgUkyKAZ1
    endpoint: oss-cn-beijing.aliyuncs.com
  minio:
    active: true
    access-key: minio_access_key
    secret-key: felord_cn_sec_key
    endpoint: http://localhost:9000

